ADW-CHARTING
#+STARTUP: hidestars
#+STARTUP: logdone
#+AUTHOR: Ryan Davis
#+EMAIL: ryan@acceleration.net
#+TITLE: ADW-Charting TODO
#+OPTIONS: num:nil

* Fall 2008
** process incoming patches
   have gotten a few via email
** port documentation to be exported org file(s)
   the current docs are generated using cl-who, and there's a lot of
   code in doc.lisp that recreates the [[http://www.gnu.org/software/emacs/manual/html_node/org/HTML-export.html#HTML-export][org-mode HTML export]].  Probably
   want three files:
   - this todo
   - introduction with examples
   - API description
** add bar charts to documentation
** add documentation for google charts
** review vecto backend, refactor with current knowledge
   when I wrote a lot of this I was obsessed with mapcar and unfamilair with loop,
   and much code can be eliminated or made much clearer with loop
** pull google simplifications into other code
** rework vecto backend to use new vecto features
   At least strip out the broken pie-chart masking crap and use vecto's [[http://www.xach.com/lisp/vecto/#arc][arc]] or arcn function,
   but review the [[http://www.xach.com/lisp/vecto/][vecto docs]] and see what else could be applicable.
** signal an error when specifying a google chart that is too big for the google service
   maybe provide a restart to use the biggest valid height/width that keeps the aspect ratio?
** pull in alexandria for common utils
   might not be needed
* Spring 2009
** unify the API
   make everything be (with-chart(:type ...)) instead of (with-type-chart(...))
** look at a smarter way to pick points/labels/bounds
   - make many passes to see what will fit?
   - maybe something like cl-unification or lisa would help?
** get it asdf-installable
* Future
** move into a different place on clnet containing other ADW libraries
   We have a growing number of libraries at work that could be opened up,
   and it might be best to have an "ADW" umbrella project similar to arnesi to
   contain our many sub-projects.
   
